# Generated by Django 5.2.8 on 2025-12-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='users.company'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.companyproject'),
        ),
        migrations.AddIndex(
            model_name='companyproject',
            index=models.Index(fields=['company', 'is_active'], name='projects_co_company_c5108d_idx'),
        ),
    ]
