# Generated by Django 5.2.8 on 2025-12-19 13:04

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0002_alter_company_options_alter_user_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Картинка проекта', 'verbose_name_plural': 'Картинки проекта'},
        ),
        migrations.RemoveField(
            model_name='companyproject',
            name='name',
        ),
        migrations.AddField(
            model_name='companyproject',
            name='features',
            field=models.TextField(blank=True, verbose_name='Особенности проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Цель проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/hero/%Y/%m/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='role_in_project',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Наша роль в проекте'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='task',
            field=models.TextField(blank=True, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyproject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='users.company', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='companyproject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание полное'),
        ),
        migrations.AlterField(
            model_name='companyproject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('value', models.CharField(max_length=180, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='projects.companyproject')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
