# Generated by Django 5.2.8 on 2025-12-19 13:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyproject',
            name='description',
        ),
        migrations.AddField(
            model_name='companyproject',
            name='customer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='power_mw',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность, МВт'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='project_type',
            field=models.CharField(blank=True, max_length=250, verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='companyproject',
            name='features',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Особенности проекта'),
        ),
        migrations.AlterField(
            model_name='companyproject',
            name='goal',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Цель проекта'),
        ),
        migrations.AlterField(
            model_name='companyproject',
            name='summary',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='companyproject',
            name='task',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Задача'),
        ),
    ]
