# Generated by Django 5.2.8 on 2025-12-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_companyproject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproject',
            name='map_x',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Точка на карте X (0..1)'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='map_y',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Точка на карте Y (0..1)'),
        ),
    ]
