# Generated by Django 5.2.8 on 2025-12-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_companyproject_map_x_companyproject_map_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstat',
            name='project',
        ),
        migrations.RemoveIndex(
            model_name='companyproject',
            name='projects_co_company_c5108d_idx',
        ),
        migrations.RemoveField(
            model_name='companyproject',
            name='company',
        ),
        migrations.AddIndex(
            model_name='companyproject',
            index=models.Index(fields=['is_active'], name='projects_co_is_acti_9d3dd3_idx'),
        ),
        migrations.DeleteModel(
            name='ProjectStat',
        ),
    ]
