# Generated by Django 5.2.8 on 2025-12-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projectstat_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='is_cover',
        ),
    ]
