# Generated by Django 5.2.8 on 2025-12-25 14:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_projectimage_is_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproject',
            name='customer_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='customer_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='customer_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='features_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Особенности проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='features_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Особенности проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='features_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Особенности проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='goal_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Цель проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='goal_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Цель проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='goal_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Цель проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='location_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='location_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='location_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='project_type_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='project_type_kk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='project_type_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='role_in_project_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Наша роль в проекте'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='role_in_project_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Наша роль в проекте'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='role_in_project_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Наша роль в проекте'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='summary_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='summary_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='summary_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='task_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='task_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='task_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
    ]
