# Generated by Django 5.2.8 on 2025-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_companyproject_customer_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='power_mw',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Мощность, МВт'),
        ),
    ]
