# Generated by Django 5.2.8 on 2025-12-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_companyproject_power_mw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='projects/hero/%Y/%m/', verbose_name='Главное изображение'),
        ),
    ]
