# Generated by Django 5.2.8 on 2025-12-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_companyproject_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproject',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='projects/hero/%Y/%m/', verbose_name='Главное видео'),
        ),
    ]
